server:
 port: 9001
spring:
 application:
  name: eurka-server
eureka:
 client:
  service-url:
   #集群配置：defaultZone: http://localhost:9002/eureka/,http://localhost:9003/eureka/
   defaultZone: http://localhost:9001/eureka/
